---
# defaults file for netdata
netdata_install_dir: /opt
netdata_systemd: True
netdata_deps:
  - zlib1g-dev
  - uuid-dev
  - libmnl-dev
  - gcc
  - make
  - git
  - autoconf
  - autoconf-archive
  - autogen
  - automake
  - pkg-config
  - curl
netdata_version: v1.13.0
