---
  - name: PIHOLE | Check if present
    stat:
      path: "{{pihole_install_dir}}"
    register: pihole_present
  - debug: msg="pi-hole not installed"
    when: pihole_present.stat.exists == False
  - debug: msg="pi-hole installed"
    when: pihole_present.stat.exists == True

  - name: Creates temp directory
    file:
      path: /tmp/pihole
      state: directory
      mode: 0777
    when: pihole_present.stat.exists == False
    tags:
      - pihole
  
  - name: PIHOLE | Download install script
    get_url:
      url: https://install.pi-hole.net
      dest: /tmp/pihole/basic-install.sh
      mode: 0777
    register: pihole_download
    when: pihole_present.stat.exists == False
    tags:
      - pihole
  - debug: var=pihole_download

  - name: HASSIO | Run install
    shell: "./basic-install.sh"
    args:
      chdir: /tmp/pihole
    when: pihole_download.status_code is defined and pihole_download.status_code == 200
    become: yes
    tags:
      - pihole
